/*CURSOR*/

DECLARE
CURSOR C1 IS SELECT * FROM BILL_DETAILS;
Dnew NUMBER;
BEGIN
FOR REC IN C1 LOOP
IF REC.DISCOUNT_AMT=20 THEN
Dnew:=30;
else
Dnew:=REC.DISCOUNT_AMT;
END IF;
Update BILL_DETAILS SET DISCOUNT_AMT=Dnew WHERE BILL_NO=REC.BILL_NO;
END LOOP;
END;
/